targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            x_database: lib/data/database.dart
          test_dir: test/drift/
          schema_dir: drift_schemas/
          store_date_time_values_as_text: true