// Mocks generated by Mockito 5.4.6 from annotations
// in vx/test/unit_test/auto_update_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i8;

import 'package:fixnum/fixnum.dart' as _i13;
import 'package:flutter/material.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:tm/protos/protos/router.pb.dart' as _i3;
import 'package:tm/protos/protos/tun.pb.dart' as _i5;
import 'package:vx/app/blocs/proxy_selector/proxy_selector_bloc.dart' as _i11;
import 'package:vx/app/control.dart' as _i12;
import 'package:vx/app/home/home.dart' as _i15;
import 'package:vx/app/outbound/outbound_page.dart' as _i17;
import 'package:vx/app/outbound/outbound_repo.dart' as _i2;
import 'package:vx/app/outbound/outbounds_bloc.dart' as _i4;
import 'package:vx/pref_helper.dart' as _i9;
import 'package:vx/utils/auto_update_service.dart' as _i16;
import 'package:vx/utils/download.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOutboundRepo_0 extends _i1.SmartFake implements _i2.OutboundRepo {
  _FakeOutboundRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectorConfig_1 extends _i1.SmartFake
    implements _i3.SelectorConfig {
  _FakeSelectorConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectorConfig_BalanceStrategy_2 extends _i1.SmartFake
    implements _i3.SelectorConfig_BalanceStrategy {
  _FakeSelectorConfig_BalanceStrategy_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOutboundTableSmallScreenPreference_3 extends _i1.SmartFake
    implements _i4.OutboundTableSmallScreenPreference {
  _FakeOutboundTableSmallScreenPreference_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTunConfig_TUN46Setting_4 extends _i1.SmartFake
    implements _i5.TunConfig_TUN46Setting {
  _FakeTunConfig_TUN46Setting_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Downloader].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloader extends _i1.Mock implements _i6.Downloader {
  MockDownloader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OutboundRepo get outboundRepo => (super.noSuchMethod(
        Invocation.getter(#outboundRepo),
        returnValue: _FakeOutboundRepo_0(
          this,
          Invocation.getter(#outboundRepo),
        ),
      ) as _i2.OutboundRepo);

  @override
  _i7.Future<void> downloadMulti(
    List<String>? urls,
    String? dest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadMulti,
          [
            urls,
            dest,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> downloadProxyFirst(
    String? url,
    String? dest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadProxyFirst,
          [
            url,
            dest,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> download(
    String? url,
    String? dest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            url,
            dest,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> downloadZip(
    String? url,
    String? dest, {
    bool? cleanDest = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadZip,
          [
            url,
            dest,
          ],
          {#cleanDest: cleanDest},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.Uint8List> downloadMemory(String? url) => (super.noSuchMethod(
        Invocation.method(
          #downloadMemory,
          [url],
        ),
        returnValue: _i7.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i7.Future<_i8.Uint8List>);
}

/// A class which mocks [PrefHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefHelper extends _i1.Mock implements _i9.PrefHelper {
  MockPrefHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get initialLocation => (super.noSuchMethod(
        Invocation.getter(#initialLocation),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#initialLocation),
        ),
      ) as String);

  @override
  bool get initialLaunch => (super.noSuchMethod(
        Invocation.getter(#initialLaunch),
        returnValue: false,
      ) as bool);

  @override
  bool get welcomeShown => (super.noSuchMethod(
        Invocation.getter(#welcomeShown),
        returnValue: false,
      ) as bool);

  @override
  bool get databaseInitialized => (super.noSuchMethod(
        Invocation.getter(#databaseInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i11.InboundMode get inboundMode => (super.noSuchMethod(
        Invocation.getter(#inboundMode),
        returnValue: _i11.InboundMode.tun,
      ) as _i11.InboundMode);

  @override
  bool get sniff => (super.noSuchMethod(
        Invocation.getter(#sniff),
        returnValue: false,
      ) as bool);

  @override
  _i3.SelectorConfig get manualSelectorConfig => (super.noSuchMethod(
        Invocation.getter(#manualSelectorConfig),
        returnValue: _FakeSelectorConfig_1(
          this,
          Invocation.getter(#manualSelectorConfig),
        ),
      ) as _i3.SelectorConfig);

  @override
  _i11.ProxySelectorMode get proxySelectorMode => (super.noSuchMethod(
        Invocation.getter(#proxySelectorMode),
        returnValue: _i11.ProxySelectorMode.auto,
      ) as _i11.ProxySelectorMode);

  @override
  _i12.ProxySelectorManualNodeSelectionMode get proxySelectorManualMode =>
      (super.noSuchMethod(
        Invocation.getter(#proxySelectorManualMode),
        returnValue: _i12.ProxySelectorManualNodeSelectionMode.single,
      ) as _i12.ProxySelectorManualNodeSelectionMode);

  @override
  List<_i13.Int64> get proxySelectorManualLandHandlers => (super.noSuchMethod(
        Invocation.getter(#proxySelectorManualLandHandlers),
        returnValue: <_i13.Int64>[],
      ) as List<_i13.Int64>);

  @override
  _i3.SelectorConfig_BalanceStrategy
      get proxySelectorManualMultipleBalanceStrategy => (super.noSuchMethod(
            Invocation.getter(#proxySelectorManualMultipleBalanceStrategy),
            returnValue: _FakeSelectorConfig_BalanceStrategy_2(
              this,
              Invocation.getter(#proxySelectorManualMultipleBalanceStrategy),
            ),
          ) as _i3.SelectorConfig_BalanceStrategy);

  @override
  bool get enableLog => (super.noSuchMethod(
        Invocation.getter(#enableLog),
        returnValue: false,
      ) as bool);

  @override
  bool get enableDebugLog => (super.noSuchMethod(
        Invocation.getter(#enableDebugLog),
        returnValue: false,
      ) as bool);

  @override
  bool get showApp => (super.noSuchMethod(
        Invocation.getter(#showApp),
        returnValue: false,
      ) as bool);

  @override
  bool get showHandler => (super.noSuchMethod(
        Invocation.getter(#showHandler),
        returnValue: false,
      ) as bool);

  @override
  bool get fakeDns => (super.noSuchMethod(
        Invocation.getter(#fakeDns),
        returnValue: false,
      ) as bool);

  @override
  bool get autoUpdate => (super.noSuchMethod(
        Invocation.getter(#autoUpdate),
        returnValue: false,
      ) as bool);

  @override
  int get updateInterval => (super.noSuchMethod(
        Invocation.getter(#updateInterval),
        returnValue: 0,
      ) as int);

  @override
  bool get hasShownOnce => (super.noSuchMethod(
        Invocation.getter(#hasShownOnce),
        returnValue: false,
      ) as bool);

  @override
  bool get proxyShare => (super.noSuchMethod(
        Invocation.getter(#proxyShare),
        returnValue: false,
      ) as bool);

  @override
  String get proxyShareListenAddress => (super.noSuchMethod(
        Invocation.getter(#proxyShareListenAddress),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#proxyShareListenAddress),
        ),
      ) as String);

  @override
  int get proxyShareListenPort => (super.noSuchMethod(
        Invocation.getter(#proxyShareListenPort),
        returnValue: 0,
      ) as int);

  @override
  String get socksUdpAssociateAddress => (super.noSuchMethod(
        Invocation.getter(#socksUdpAssociateAddress),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#socksUdpAssociateAddress),
        ),
      ) as String);

  @override
  double get windowWidth => (super.noSuchMethod(
        Invocation.getter(#windowWidth),
        returnValue: 0.0,
      ) as double);

  @override
  double get windowHeight => (super.noSuchMethod(
        Invocation.getter(#windowHeight),
        returnValue: 0.0,
      ) as double);

  @override
  bool get smScreenShowProtocol => (super.noSuchMethod(
        Invocation.getter(#smScreenShowProtocol),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowOk => (super.noSuchMethod(
        Invocation.getter(#smScreenShowOk),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowSpeed => (super.noSuchMethod(
        Invocation.getter(#smScreenShowSpeed),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowLatency => (super.noSuchMethod(
        Invocation.getter(#smScreenShowLatency),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowActive => (super.noSuchMethod(
        Invocation.getter(#smScreenShowActive),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowAddress => (super.noSuchMethod(
        Invocation.getter(#smScreenShowAddress),
        returnValue: false,
      ) as bool);

  @override
  String get outboundViewMode => (super.noSuchMethod(
        Invocation.getter(#outboundViewMode),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#outboundViewMode),
        ),
      ) as String);

  @override
  _i4.OutboundTableSmallScreenPreference
      get outboundTableSmallScreenPreference => (super.noSuchMethod(
            Invocation.getter(#outboundTableSmallScreenPreference),
            returnValue: _FakeOutboundTableSmallScreenPreference_3(
              this,
              Invocation.getter(#outboundTableSmallScreenPreference),
            ),
          ) as _i4.OutboundTableSmallScreenPreference);

  @override
  bool get shareLog => (super.noSuchMethod(
        Invocation.getter(#shareLog),
        returnValue: false,
      ) as bool);

  @override
  bool get advanceRouteMode => (super.noSuchMethod(
        Invocation.getter(#advanceRouteMode),
        returnValue: false,
      ) as bool);

  @override
  _i5.TunConfig_TUN46Setting get tun46Setting => (super.noSuchMethod(
        Invocation.getter(#tun46Setting),
        returnValue: _FakeTunConfig_TUN46Setting_4(
          this,
          Invocation.getter(#tun46Setting),
        ),
      ) as _i5.TunConfig_TUN46Setting);

  @override
  _i14.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i14.ThemeMode.system,
      ) as _i14.ThemeMode);

  @override
  bool get windowsServiceInstalled => (super.noSuchMethod(
        Invocation.getter(#windowsServiceInstalled),
        returnValue: false,
      ) as bool);

  @override
  bool get fallbackToProxy => (super.noSuchMethod(
        Invocation.getter(#fallbackToProxy),
        returnValue: false,
      ) as bool);

  @override
  bool get fallbackRetryDomain => (super.noSuchMethod(
        Invocation.getter(#fallbackRetryDomain),
        returnValue: false,
      ) as bool);

  @override
  _i9.PingMode get pingMode => (super.noSuchMethod(
        Invocation.getter(#pingMode),
        returnValue: _i9.PingMode.Real,
      ) as _i9.PingMode);

  @override
  bool get alwaysOn => (super.noSuchMethod(
        Invocation.getter(#alwaysOn),
        returnValue: false,
      ) as bool);

  @override
  bool get startOnBoot => (super.noSuchMethod(
        Invocation.getter(#startOnBoot),
        returnValue: false,
      ) as bool);

  @override
  bool get connect => (super.noSuchMethod(
        Invocation.getter(#connect),
        returnValue: false,
      ) as bool);

  @override
  int get socksPort => (super.noSuchMethod(
        Invocation.getter(#socksPort),
        returnValue: 0,
      ) as int);

  @override
  int get httpPort => (super.noSuchMethod(
        Invocation.getter(#httpPort),
        returnValue: 0,
      ) as int);

  @override
  bool get dynamicSystemProxyPorts => (super.noSuchMethod(
        Invocation.getter(#dynamicSystemProxyPorts),
        returnValue: false,
      ) as bool);

  @override
  bool get rejectQuicHysteria => (super.noSuchMethod(
        Invocation.getter(#rejectQuicHysteria),
        returnValue: false,
      ) as bool);

  @override
  bool get cloudSync => (super.noSuchMethod(
        Invocation.getter(#cloudSync),
        returnValue: false,
      ) as bool);

  @override
  bool get syncNodeSub => (super.noSuchMethod(
        Invocation.getter(#syncNodeSub),
        returnValue: false,
      ) as bool);

  @override
  bool get syncRoute => (super.noSuchMethod(
        Invocation.getter(#syncRoute),
        returnValue: false,
      ) as bool);

  @override
  bool get syncSelectorSetting => (super.noSuchMethod(
        Invocation.getter(#syncSelectorSetting),
        returnValue: false,
      ) as bool);

  @override
  bool get syncServer => (super.noSuchMethod(
        Invocation.getter(#syncServer),
        returnValue: false,
      ) as bool);

  @override
  int get machineId => (super.noSuchMethod(
        Invocation.getter(#machineId),
        returnValue: 0,
      ) as int);

  @override
  bool get autoBackup => (super.noSuchMethod(
        Invocation.getter(#autoBackup),
        returnValue: false,
      ) as bool);

  @override
  String get dbName => (super.noSuchMethod(
        Invocation.getter(#dbName),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#dbName),
        ),
      ) as String);

  @override
  bool get storeSudoPasswordInMemory => (super.noSuchMethod(
        Invocation.getter(#storeSudoPasswordInMemory),
        returnValue: false,
      ) as bool);

  @override
  bool get showRpmNotice => (super.noSuchMethod(
        Invocation.getter(#showRpmNotice),
        returnValue: false,
      ) as bool);

  @override
  bool get autoTestNodes => (super.noSuchMethod(
        Invocation.getter(#autoTestNodes),
        returnValue: false,
      ) as bool);

  @override
  int get nodeTestInterval => (super.noSuchMethod(
        Invocation.getter(#nodeTestInterval),
        returnValue: 0,
      ) as int);

  @override
  _i15.NodesHelperSegment get nodesHelperSegment => (super.noSuchMethod(
        Invocation.getter(#nodesHelperSegment),
        returnValue: _i15.NodesHelperSegment.fastest,
      ) as _i15.NodesHelperSegment);

  @override
  set enableLog(bool? enable) => super.noSuchMethod(
        Invocation.setter(
          #enableLog,
          enable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInitialLocation(String? location) => super.noSuchMethod(
        Invocation.method(
          #setInitialLocation,
          [location],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInitialLaunch() => super.noSuchMethod(
        Invocation.method(
          #setInitialLaunch,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWelcomeShown(bool? shown) => super.noSuchMethod(
        Invocation.method(
          #setWelcomeShown,
          [shown],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDatabaseInitialized(bool? initialized) => super.noSuchMethod(
        Invocation.method(
          #setDatabaseInitialized,
          [initialized],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInboundMode(_i11.InboundMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setInboundMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSniff(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSniff,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRoutingMode(String? mode) => super.noSuchMethod(
        Invocation.method(
          #setRoutingMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorMode(_i11.ProxySelectorMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setProxySelectorMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorManualMode(
          _i12.ProxySelectorManualNodeSelectionMode? mode) =>
      super.noSuchMethod(
        Invocation.method(
          #setProxySelectorManualMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorLandHandlers(List<_i13.Int64>? ids) =>
      super.noSuchMethod(
        Invocation.method(
          #setProxySelectorLandHandlers,
          [ids],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorManualMultipleBalanceStrategy(
          _i3.SelectorConfig_BalanceStrategy? strategy) =>
      super.noSuchMethod(
        Invocation.method(
          #setProxySelectorManualMultipleBalanceStrategy,
          [strategy],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEnableDebugLog(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setEnableDebugLog,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowApp(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setShowApp,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowHandler(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setShowHandler,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastGeoUpdate(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastGeoUpdate,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFakeDns(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setFakeDns,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoUpdate(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAutoUpdate,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUpdateInterval(int? interval) => super.noSuchMethod(
        Invocation.method(
          #setUpdateInterval,
          [interval],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastUpdateCheckTime(int? timestamp) => super.noSuchMethod(
        Invocation.method(
          #setLastUpdateCheckTime,
          [timestamp],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDownloadedInstallerPath(_i16.DownloadedInstaller? installer) =>
      super.noSuchMethod(
        Invocation.method(
          #setDownloadedInstallerPath,
          [installer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSkipVersion(String? version) => super.noSuchMethod(
        Invocation.method(
          #setSkipVersion,
          [version],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLanguage(_i9.Language? language) => super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHasShownOnce(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setHasShownOnce,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxyShare(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setProxyShare,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxyShareListenAddress(String? address) => super.noSuchMethod(
        Invocation.method(
          #setProxyShareListenAddress,
          [address],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxyShareListenPort(int? port) => super.noSuchMethod(
        Invocation.method(
          #setProxyShareListenPort,
          [port],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSocksUdpaccociateAddress(String? addr) => super.noSuchMethod(
        Invocation.method(
          #setSocksUdpaccociateAddress,
          [addr],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowX(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowX,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowY(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowY,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowWidth(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowWidth,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowHeight(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowHeight,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowProtocol(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowProtocol,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowOk(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowOk,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowSpeed(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowSpeed,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowActive(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowActive,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowLatency(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowLatency,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowAddress(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowAddress,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOutboundViewMode(_i4.OutboundViewMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setOutboundViewMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShareLog(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setShareLog,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastUploadTime(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastUploadTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSortCol((_i17.Col, int)? col) => super.noSuchMethod(
        Invocation.method(
          #setSortCol,
          [col],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNodeGroup(String? group) => super.noSuchMethod(
        Invocation.method(
          #setNodeGroup,
          [group],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAdvanceRouteMode(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAdvanceRouteMode,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTun46Setting(_i5.TunConfig_TUN46Setting? setting) =>
      super.noSuchMethod(
        Invocation.method(
          #setTun46Setting,
          [setting],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setThemeMode(_i14.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowsServiceInstalled(bool? installed) => super.noSuchMethod(
        Invocation.method(
          #setWindowsServiceInstalled,
          [installed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFallbackToProxy(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setFallbackToProxy,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFallbackRetryDomain(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setFallbackRetryDomain,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPingMode(_i9.PingMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setPingMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAlwaysOn(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAlwaysOn,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStartOnBoot(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setStartOnBoot,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setConnect(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setConnect,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSocksPort(int? port) => super.noSuchMethod(
        Invocation.method(
          #setSocksPort,
          [port],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHttpPort(int? port) => super.noSuchMethod(
        Invocation.method(
          #setHttpPort,
          [port],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDynamicSystemProxyPorts(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setDynamicSystemProxyPorts,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRejectQuicHysteria(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setRejectQuicHysteria,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCloudSync(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setCloudSync,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncNodeSub(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncNodeSub,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncRuleDnsSet(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncRuleDnsSet,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncSelectorSetting(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncSelectorSetting,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncServer(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncServer,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDeviceIdUpdateTime(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setDeviceIdUpdateTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFcmToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setFcmToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoBackup(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAutoBackup,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDbName(String? name) => super.noSuchMethod(
        Invocation.method(
          #setDbName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStoreSudoPasswordInMemory(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setStoreSudoPasswordInMemory,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowRpmNotice(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setShowRpmNotice,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoTestNodes(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAutoTestNodes,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNodeTestInterval(int? minutes) => super.noSuchMethod(
        Invocation.method(
          #setNodeTestInterval,
          [minutes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastNodeTestTime(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastNodeTestTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNodesHelperSegment(_i15.NodesHelperSegment? segment) =>
      super.noSuchMethod(
        Invocation.method(
          #setNodesHelperSegment,
          [segment],
        ),
        returnValueForMissingStub: null,
      );
}
