// Mocks generated by Mockito 5.4.6 from annotations
// in vx/test/unit_test/geodata_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i12;

import 'package:drift/drift.dart' as _i8;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i9;
import 'package:fixnum/fixnum.dart' as _i16;
import 'package:flutter/material.dart' as _i19;
import 'package:grpc/grpc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:tm/protos/app/api/api.pbgrpc.dart' as _i5;
import 'package:tm/protos/common/geo/geo.pb.dart' as _i23;
import 'package:tm/protos/protos/geo.pb.dart' as _i24;
import 'package:tm/protos/protos/router.pb.dart' as _i3;
import 'package:tm/protos/protos/sysproxy.pb.dart' as _i25;
import 'package:tm/protos/protos/tun.pb.dart' as _i4;
import 'package:vx/app/control.dart' as _i15;
import 'package:vx/app/outbound/outbound_page.dart' as _i21;
import 'package:vx/app/outbound/outbound_repo.dart' as _i2;
import 'package:vx/app/outbound/outbounds_bloc.dart' as _i20;
import 'package:vx/app/blocs/proxy_selector/proxy_selector_bloc.dart' as _i14;
import 'package:vx/data/database.dart' as _i7;
import 'package:vx/data/database_helper.dart' as _i26;
import 'package:vx/pref_helper.dart' as _i13;
import 'package:vx/utils/download.dart' as _i11;
import 'package:vx/utils/xapi_client.dart' as _i22;
import 'package:vx/xconfig_helper.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOutboundRepo_0 extends _i1.SmartFake implements _i2.OutboundRepo {
  _FakeOutboundRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectorConfig_1 extends _i1.SmartFake
    implements _i3.SelectorConfig {
  _FakeSelectorConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectorConfig_BalanceStrategy_2 extends _i1.SmartFake
    implements _i3.SelectorConfig_BalanceStrategy {
  _FakeSelectorConfig_BalanceStrategy_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTunConfig_TUN46Setting_3 extends _i1.SmartFake
    implements _i4.TunConfig_TUN46Setting {
  _FakeTunConfig_TUN46Setting_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownloadResponse_4 extends _i1.SmartFake
    implements _i5.DownloadResponse {
  _FakeDownloadResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHandlerUsableResponse_5 extends _i1.SmartFake
    implements _i5.HandlerUsableResponse {
  _FakeHandlerUsableResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStream_6<R> extends _i1.SmartFake
    implements _i6.ResponseStream<R> {
  _FakeResponseStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeoIPResponse_7 extends _i1.SmartFake implements _i5.GeoIPResponse {
  _FakeGeoIPResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateSubscriptionResponse_8 extends _i1.SmartFake
    implements _i5.UpdateSubscriptionResponse {
  _FakeUpdateSubscriptionResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDecodeResponse_9 extends _i1.SmartFake
    implements _i5.DecodeResponse {
  _FakeDecodeResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerateCertResponse_10 extends _i1.SmartFake
    implements _i5.GenerateCertResponse {
  _FakeGenerateCertResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParseClashRuleFileResponse_11 extends _i1.SmartFake
    implements _i5.ParseClashRuleFileResponse {
  _FakeParseClashRuleFileResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppDatabase_12 extends _i1.SmartFake implements _i7.AppDatabase {
  _FakeAppDatabase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_13 extends _i1.SmartFake
    implements _i8.MigrationStrategy {
  _FakeMigrationStrategy_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SubscriptionsTable_14 extends _i1.SmartFake
    implements _i7.$SubscriptionsTable {
  _Fake$SubscriptionsTable_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$OutboundHandlersTable_15 extends _i1.SmartFake
    implements _i7.$OutboundHandlersTable {
  _Fake$OutboundHandlersTable_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$OutboundHandlerGroupsTable_16 extends _i1.SmartFake
    implements _i7.$OutboundHandlerGroupsTable {
  _Fake$OutboundHandlerGroupsTable_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$OutboundHandlerGroupRelationsTable_17 extends _i1.SmartFake
    implements _i7.$OutboundHandlerGroupRelationsTable {
  _Fake$OutboundHandlerGroupRelationsTable_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$DnsRecordsTable_18 extends _i1.SmartFake
    implements _i7.$DnsRecordsTable {
  _Fake$DnsRecordsTable_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AtomicDomainSetsTable_19 extends _i1.SmartFake
    implements _i7.$AtomicDomainSetsTable {
  _Fake$AtomicDomainSetsTable_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$GeoDomainsTable_20 extends _i1.SmartFake
    implements _i7.$GeoDomainsTable {
  _Fake$GeoDomainsTable_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$GreatDomainSetsTable_21 extends _i1.SmartFake
    implements _i7.$GreatDomainSetsTable {
  _Fake$GreatDomainSetsTable_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AtomicIpSetsTable_22 extends _i1.SmartFake
    implements _i7.$AtomicIpSetsTable {
  _Fake$AtomicIpSetsTable_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$GreatIpSetsTable_23 extends _i1.SmartFake
    implements _i7.$GreatIpSetsTable {
  _Fake$GreatIpSetsTable_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppSetsTable_24 extends _i1.SmartFake implements _i7.$AppSetsTable {
  _Fake$AppSetsTable_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppsTable_25 extends _i1.SmartFake implements _i7.$AppsTable {
  _Fake$AppsTable_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CidrsTable_26 extends _i1.SmartFake implements _i7.$CidrsTable {
  _Fake$CidrsTable_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SshServersTable_27 extends _i1.SmartFake
    implements _i7.$SshServersTable {
  _Fake$SshServersTable_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CommonSshKeysTable_28 extends _i1.SmartFake
    implements _i7.$CommonSshKeysTable {
  _Fake$CommonSshKeysTable_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CustomRouteModesTable_29 extends _i1.SmartFake
    implements _i7.$CustomRouteModesTable {
  _Fake$CustomRouteModesTable_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$HandlerSelectorsTable_30 extends _i1.SmartFake
    implements _i7.$HandlerSelectorsTable {
  _Fake$HandlerSelectorsTable_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SelectorHandlerRelationsTable_31 extends _i1.SmartFake
    implements _i7.$SelectorHandlerRelationsTable {
  _Fake$SelectorHandlerRelationsTable_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SelectorHandlerGroupRelationsTable_32 extends _i1.SmartFake
    implements _i7.$SelectorHandlerGroupRelationsTable {
  _Fake$SelectorHandlerGroupRelationsTable_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SelectorSubscriptionRelationsTable_33 extends _i1.SmartFake
    implements _i7.$SelectorSubscriptionRelationsTable {
  _Fake$SelectorSubscriptionRelationsTable_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$DnsServersTable_34 extends _i1.SmartFake
    implements _i7.$DnsServersTable {
  _Fake$DnsServersTable_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppDatabaseManager_35 extends _i1.SmartFake
    implements _i7.$AppDatabaseManager {
  _Fake$AppDatabaseManager_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_36 extends _i1.SmartFake
    implements _i8.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_37 extends _i1.SmartFake
    implements _i8.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_38 extends _i1.SmartFake
    implements _i8.GeneratedDatabase {
  _FakeGeneratedDatabase_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_39 extends _i1.SmartFake
    implements _i8.DatabaseConnection {
  _FakeDatabaseConnection_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_40 extends _i1.SmartFake implements _i8.QueryExecutor {
  _FakeQueryExecutor_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_41 extends _i1.SmartFake
    implements _i9.StreamQueryStore {
  _FakeStreamQueryStore_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_42 extends _i1.SmartFake
    implements _i8.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_43 extends _i1.SmartFake implements _i8.Migrator {
  _FakeMigrator_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_44<T1> extends _i1.SmartFake implements _i10.Future<T1> {
  _FakeFuture_44(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_45<T1 extends _i8.Table, D1> extends _i1.SmartFake
    implements _i8.InsertStatement<T1, D1> {
  _FakeInsertStatement_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_46<T extends _i8.Table, D> extends _i1.SmartFake
    implements _i8.UpdateStatement<T, D> {
  _FakeUpdateStatement_46(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_47<T1 extends _i8.HasResultSet, D>
    extends _i1.SmartFake implements _i8.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_47(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_48<FirstT extends _i8.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i8.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_48(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_49<Row> extends _i1.SmartFake
    implements _i8.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_49(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_50<T1 extends _i8.Table, D1> extends _i1.SmartFake
    implements _i8.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_50(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_51<T> extends _i1.SmartFake implements _i8.Selectable<T> {
  _FakeSelectable_51(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_52 extends _i1.SmartFake
    implements _i8.GenerationContext {
  _FakeGenerationContext_52(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAtomicDomainSetsCompanion_53 extends _i1.SmartFake
    implements _i7.AtomicDomainSetsCompanion {
  _FakeAtomicDomainSetsCompanion_53(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppSetsCompanion_54 extends _i1.SmartFake
    implements _i7.AppSetsCompanion {
  _FakeAppSetsCompanion_54(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAtomicIpSetsCompanion_55 extends _i1.SmartFake
    implements _i7.AtomicIpSetsCompanion {
  _FakeAtomicIpSetsCompanion_55(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Downloader].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloader extends _i1.Mock implements _i11.Downloader {
  MockDownloader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OutboundRepo get outboundRepo => (super.noSuchMethod(
        Invocation.getter(#outboundRepo),
        returnValue: _FakeOutboundRepo_0(
          this,
          Invocation.getter(#outboundRepo),
        ),
      ) as _i2.OutboundRepo);

  @override
  _i10.Future<void> downloadMulti(
    List<String>? urls,
    String? dest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadMulti,
          [
            urls,
            dest,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> downloadProxyFirst(
    String? url,
    String? dest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadProxyFirst,
          [
            url,
            dest,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> download(
    String? url,
    String? dest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            url,
            dest,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i12.Uint8List> downloadMemory(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadMemory,
          [url],
        ),
        returnValue: _i10.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
      ) as _i10.Future<_i12.Uint8List>);
}

/// A class which mocks [PrefHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefHelper extends _i1.Mock implements _i13.PrefHelper {
  MockPrefHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get initialLaunch => (super.noSuchMethod(
        Invocation.getter(#initialLaunch),
        returnValue: false,
      ) as bool);

  @override
  bool get databaseInitialized => (super.noSuchMethod(
        Invocation.getter(#databaseInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i14.InboundMode get inboundMode => (super.noSuchMethod(
        Invocation.getter(#inboundMode),
        returnValue: _i14.InboundMode.tun,
      ) as _i14.InboundMode);

  @override
  _i3.SelectorConfig get manualSelectorConfig => (super.noSuchMethod(
        Invocation.getter(#manualSelectorConfig),
        returnValue: _FakeSelectorConfig_1(
          this,
          Invocation.getter(#manualSelectorConfig),
        ),
      ) as _i3.SelectorConfig);

  @override
  _i14.ProxySelectorMode get proxySelectorMode => (super.noSuchMethod(
        Invocation.getter(#proxySelectorMode),
        returnValue: _i14.ProxySelectorMode.auto,
      ) as _i14.ProxySelectorMode);

  @override
  _i15.ProxySelectorManualNodeSelectionMode get proxySelectorManualMode =>
      (super.noSuchMethod(
        Invocation.getter(#proxySelectorManualMode),
        returnValue: _i15.ProxySelectorManualNodeSelectionMode.single,
      ) as _i15.ProxySelectorManualNodeSelectionMode);

  @override
  List<_i16.Int64> get proxySelectorManualLandHandlers => (super.noSuchMethod(
        Invocation.getter(#proxySelectorManualLandHandlers),
        returnValue: <_i16.Int64>[],
      ) as List<_i16.Int64>);

  @override
  _i3.SelectorConfig_BalanceStrategy
      get proxySelectorManualMultipleBalanceStrategy => (super.noSuchMethod(
            Invocation.getter(#proxySelectorManualMultipleBalanceStrategy),
            returnValue: _FakeSelectorConfig_BalanceStrategy_2(
              this,
              Invocation.getter(#proxySelectorManualMultipleBalanceStrategy),
            ),
          ) as _i3.SelectorConfig_BalanceStrategy);

  @override
  bool get enableLog => (super.noSuchMethod(
        Invocation.getter(#enableLog),
        returnValue: false,
      ) as bool);

  @override
  bool get enableDebugLog => (super.noSuchMethod(
        Invocation.getter(#enableDebugLog),
        returnValue: false,
      ) as bool);

  @override
  bool get showApp => (super.noSuchMethod(
        Invocation.getter(#showApp),
        returnValue: false,
      ) as bool);

  @override
  bool get showHandler => (super.noSuchMethod(
        Invocation.getter(#showHandler),
        returnValue: false,
      ) as bool);

  @override
  bool get fakeDns => (super.noSuchMethod(
        Invocation.getter(#fakeDns),
        returnValue: false,
      ) as bool);

  @override
  bool get autoUpdate => (super.noSuchMethod(
        Invocation.getter(#autoUpdate),
        returnValue: false,
      ) as bool);

  @override
  int get updateInterval => (super.noSuchMethod(
        Invocation.getter(#updateInterval),
        returnValue: 0,
      ) as int);

  @override
  bool get hasShownOnce => (super.noSuchMethod(
        Invocation.getter(#hasShownOnce),
        returnValue: false,
      ) as bool);

  @override
  bool get proxyShare => (super.noSuchMethod(
        Invocation.getter(#proxyShare),
        returnValue: false,
      ) as bool);

  @override
  String get proxyShareListenAddress => (super.noSuchMethod(
        Invocation.getter(#proxyShareListenAddress),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#proxyShareListenAddress),
        ),
      ) as String);

  @override
  int get proxyShareListenPort => (super.noSuchMethod(
        Invocation.getter(#proxyShareListenPort),
        returnValue: 0,
      ) as int);

  @override
  String get socksUdpAssociateAddress => (super.noSuchMethod(
        Invocation.getter(#socksUdpAssociateAddress),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#socksUdpAssociateAddress),
        ),
      ) as String);

  @override
  double get windowWidth => (super.noSuchMethod(
        Invocation.getter(#windowWidth),
        returnValue: 0.0,
      ) as double);

  @override
  double get windowHeight => (super.noSuchMethod(
        Invocation.getter(#windowHeight),
        returnValue: 0.0,
      ) as double);

  @override
  bool get smScreenShowProtocol => (super.noSuchMethod(
        Invocation.getter(#smScreenShowProtocol),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowOk => (super.noSuchMethod(
        Invocation.getter(#smScreenShowOk),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowSpeed => (super.noSuchMethod(
        Invocation.getter(#smScreenShowSpeed),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowLatency => (super.noSuchMethod(
        Invocation.getter(#smScreenShowLatency),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowActive => (super.noSuchMethod(
        Invocation.getter(#smScreenShowActive),
        returnValue: false,
      ) as bool);

  @override
  bool get smScreenShowAddress => (super.noSuchMethod(
        Invocation.getter(#smScreenShowAddress),
        returnValue: false,
      ) as bool);

  @override
  String get outboundViewMode => (super.noSuchMethod(
        Invocation.getter(#outboundViewMode),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#outboundViewMode),
        ),
      ) as String);

  @override
  bool get shareLog => (super.noSuchMethod(
        Invocation.getter(#shareLog),
        returnValue: false,
      ) as bool);

  @override
  bool get advanceRouteMode => (super.noSuchMethod(
        Invocation.getter(#advanceRouteMode),
        returnValue: false,
      ) as bool);

  @override
  _i18.SniffPreference get sniffPreference => (super.noSuchMethod(
        Invocation.getter(#sniffPreference),
        returnValue: _i18.SniffPreference.disable,
      ) as _i18.SniffPreference);

  @override
  _i4.TunConfig_TUN46Setting get tun46Setting => (super.noSuchMethod(
        Invocation.getter(#tun46Setting),
        returnValue: _FakeTunConfig_TUN46Setting_3(
          this,
          Invocation.getter(#tun46Setting),
        ),
      ) as _i4.TunConfig_TUN46Setting);

  @override
  _i19.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i19.ThemeMode.system,
      ) as _i19.ThemeMode);

  @override
  bool get windowsServiceInstalled => (super.noSuchMethod(
        Invocation.getter(#windowsServiceInstalled),
        returnValue: false,
      ) as bool);

  @override
  bool get fallbackToProxy => (super.noSuchMethod(
        Invocation.getter(#fallbackToProxy),
        returnValue: false,
      ) as bool);

  @override
  bool get fallbackRetryDomain => (super.noSuchMethod(
        Invocation.getter(#fallbackRetryDomain),
        returnValue: false,
      ) as bool);

  @override
  _i13.PingMode get pingMode => (super.noSuchMethod(
        Invocation.getter(#pingMode),
        returnValue: _i13.PingMode.Real,
      ) as _i13.PingMode);

  @override
  bool get alwaysOn => (super.noSuchMethod(
        Invocation.getter(#alwaysOn),
        returnValue: false,
      ) as bool);

  @override
  bool get startOnBoot => (super.noSuchMethod(
        Invocation.getter(#startOnBoot),
        returnValue: false,
      ) as bool);

  @override
  bool get connect => (super.noSuchMethod(
        Invocation.getter(#connect),
        returnValue: false,
      ) as bool);

  @override
  int get socksPort => (super.noSuchMethod(
        Invocation.getter(#socksPort),
        returnValue: 0,
      ) as int);

  @override
  int get httpPort => (super.noSuchMethod(
        Invocation.getter(#httpPort),
        returnValue: 0,
      ) as int);

  @override
  bool get dynamicSystemProxyPorts => (super.noSuchMethod(
        Invocation.getter(#dynamicSystemProxyPorts),
        returnValue: false,
      ) as bool);

  @override
  bool get rejectQuicHysteria => (super.noSuchMethod(
        Invocation.getter(#rejectQuicHysteria),
        returnValue: false,
      ) as bool);

  @override
  bool get cloudSync => (super.noSuchMethod(
        Invocation.getter(#cloudSync),
        returnValue: false,
      ) as bool);

  @override
  bool get syncNodeSub => (super.noSuchMethod(
        Invocation.getter(#syncNodeSub),
        returnValue: false,
      ) as bool);

  @override
  bool get syncRoute => (super.noSuchMethod(
        Invocation.getter(#syncRoute),
        returnValue: false,
      ) as bool);

  @override
  bool get syncSelectorSetting => (super.noSuchMethod(
        Invocation.getter(#syncSelectorSetting),
        returnValue: false,
      ) as bool);

  @override
  bool get syncServer => (super.noSuchMethod(
        Invocation.getter(#syncServer),
        returnValue: false,
      ) as bool);

  @override
  int get machineId => (super.noSuchMethod(
        Invocation.getter(#machineId),
        returnValue: 0,
      ) as int);

  @override
  bool get autoBackup => (super.noSuchMethod(
        Invocation.getter(#autoBackup),
        returnValue: false,
      ) as bool);

  @override
  String get dbName => (super.noSuchMethod(
        Invocation.getter(#dbName),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#dbName),
        ),
      ) as String);

  @override
  bool get storeSudoPasswordInMemory => (super.noSuchMethod(
        Invocation.getter(#storeSudoPasswordInMemory),
        returnValue: false,
      ) as bool);

  @override
  bool get showRpmNotice => (super.noSuchMethod(
        Invocation.getter(#showRpmNotice),
        returnValue: false,
      ) as bool);

  @override
  set enableLog(bool? enable) => super.noSuchMethod(
        Invocation.setter(
          #enableLog,
          enable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInitialLaunch() => super.noSuchMethod(
        Invocation.method(
          #setInitialLaunch,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDatabaseInitialized(bool? initialized) => super.noSuchMethod(
        Invocation.method(
          #setDatabaseInitialized,
          [initialized],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInboundMode(_i14.InboundMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setInboundMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRoutingMode(String? mode) => super.noSuchMethod(
        Invocation.method(
          #setRoutingMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorMode(_i14.ProxySelectorMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setProxySelectorMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorManualMode(
          _i15.ProxySelectorManualNodeSelectionMode? mode) =>
      super.noSuchMethod(
        Invocation.method(
          #setProxySelectorManualMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorLandHandlers(List<_i16.Int64>? ids) =>
      super.noSuchMethod(
        Invocation.method(
          #setProxySelectorLandHandlers,
          [ids],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxySelectorManualMultipleBalanceStrategy(
          _i3.SelectorConfig_BalanceStrategy? strategy) =>
      super.noSuchMethod(
        Invocation.method(
          #setProxySelectorManualMultipleBalanceStrategy,
          [strategy],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEnableDebugLog(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setEnableDebugLog,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowApp(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setShowApp,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowHandler(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setShowHandler,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastGeoUpdate(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastGeoUpdate,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFakeDns(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setFakeDns,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoUpdate(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAutoUpdate,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUpdateInterval(int? interval) => super.noSuchMethod(
        Invocation.method(
          #setUpdateInterval,
          [interval],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastUpdateCheckTime(int? timestamp) => super.noSuchMethod(
        Invocation.method(
          #setLastUpdateCheckTime,
          [timestamp],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDownloadedInstallerPath(String? path) => super.noSuchMethod(
        Invocation.method(
          #setDownloadedInstallerPath,
          [path],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSkipVersion(String? version) => super.noSuchMethod(
        Invocation.method(
          #setSkipVersion,
          [version],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLanguage(_i13.Language? language) => super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHasShownOnce(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setHasShownOnce,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxyShare(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setProxyShare,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxyShareListenAddress(String? address) => super.noSuchMethod(
        Invocation.method(
          #setProxyShareListenAddress,
          [address],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProxyShareListenPort(int? port) => super.noSuchMethod(
        Invocation.method(
          #setProxyShareListenPort,
          [port],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSocksUdpaccociateAddress(String? addr) => super.noSuchMethod(
        Invocation.method(
          #setSocksUdpaccociateAddress,
          [addr],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowX(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowX,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowY(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowY,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowWidth(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowWidth,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowHeight(double? x) => super.noSuchMethod(
        Invocation.method(
          #setWindowHeight,
          [x],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowProtocol(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowProtocol,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowOk(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowOk,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowSpeed(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowSpeed,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowActive(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowActive,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowLatency(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowLatency,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSmScreenShowAddress(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setSmScreenShowAddress,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOutboundViewMode(_i20.OutboundViewMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setOutboundViewMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShareLog(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setShareLog,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastUploadTime(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastUploadTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSortCol((_i21.Col, int)? col) => super.noSuchMethod(
        Invocation.method(
          #setSortCol,
          [col],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNodeGroup(String? group) => super.noSuchMethod(
        Invocation.method(
          #setNodeGroup,
          [group],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAdvanceRouteMode(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAdvanceRouteMode,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSniffPreference(_i18.SniffPreference? preference) =>
      super.noSuchMethod(
        Invocation.method(
          #setSniffPreference,
          [preference],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTun46Setting(_i4.TunConfig_TUN46Setting? setting) =>
      super.noSuchMethod(
        Invocation.method(
          #setTun46Setting,
          [setting],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setThemeMode(_i19.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWindowsServiceInstalled(bool? installed) => super.noSuchMethod(
        Invocation.method(
          #setWindowsServiceInstalled,
          [installed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFallbackToProxy(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setFallbackToProxy,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFallbackRetryDomain(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setFallbackRetryDomain,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPingMode(_i13.PingMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setPingMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAlwaysOn(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAlwaysOn,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStartOnBoot(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setStartOnBoot,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setConnect(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setConnect,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSocksPort(int? port) => super.noSuchMethod(
        Invocation.method(
          #setSocksPort,
          [port],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHttpPort(int? port) => super.noSuchMethod(
        Invocation.method(
          #setHttpPort,
          [port],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDynamicSystemProxyPorts(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setDynamicSystemProxyPorts,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRejectQuicHysteria(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setRejectQuicHysteria,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCloudSync(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setCloudSync,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncNodeSub(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncNodeSub,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncRuleDnsSet(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncRuleDnsSet,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncSelectorSetting(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncSelectorSetting,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSyncServer(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setSyncServer,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDeviceIdUpdateTime(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setDeviceIdUpdateTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFcmToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setFcmToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoBackup(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setAutoBackup,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDbName(String? name) => super.noSuchMethod(
        Invocation.method(
          #setDbName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStoreSudoPasswordInMemory(bool? enable) => super.noSuchMethod(
        Invocation.method(
          #setStoreSudoPasswordInMemory,
          [enable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowRpmNotice(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setShowRpmNotice,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastAdsFetchTime(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setLastAdsFetchTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [XApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockXApiClient extends _i1.Mock implements _i22.XApiClient {
  MockXApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i5.DownloadResponse> download(_i5.DownloadRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [request],
        ),
        returnValue:
            _i10.Future<_i5.DownloadResponse>.value(_FakeDownloadResponse_4(
          this,
          Invocation.method(
            #download,
            [request],
          ),
        )),
      ) as _i10.Future<_i5.DownloadResponse>);

  @override
  _i10.Future<_i5.HandlerUsableResponse> handlerUsable(
          _i5.HandlerUsableRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlerUsable,
          [request],
        ),
        returnValue: _i10.Future<_i5.HandlerUsableResponse>.value(
            _FakeHandlerUsableResponse_5(
          this,
          Invocation.method(
            #handlerUsable,
            [request],
          ),
        )),
      ) as _i10.Future<_i5.HandlerUsableResponse>);

  @override
  _i10.Future<int> rtt(_i5.RttTestRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #rtt,
          [request],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<_i6.ResponseStream<_i5.SpeedTestResponse>> speedTest(
          _i5.SpeedTestRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #speedTest,
          [request],
        ),
        returnValue:
            _i10.Future<_i6.ResponseStream<_i5.SpeedTestResponse>>.value(
                _FakeResponseStream_6<_i5.SpeedTestResponse>(
          this,
          Invocation.method(
            #speedTest,
            [request],
          ),
        )),
      ) as _i10.Future<_i6.ResponseStream<_i5.SpeedTestResponse>>);

  @override
  _i10.Future<_i5.GeoIPResponse> geoIP(_i5.GeoIPRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #geoIP,
          [request],
        ),
        returnValue: _i10.Future<_i5.GeoIPResponse>.value(_FakeGeoIPResponse_7(
          this,
          Invocation.method(
            #geoIP,
            [request],
          ),
        )),
      ) as _i10.Future<_i5.GeoIPResponse>);

  @override
  _i10.Future<_i6.ResponseStream<_i5.MonitorServerResponse>> monitorServer(
          _i7.SshServer? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorServer,
          [server],
        ),
        returnValue:
            _i10.Future<_i6.ResponseStream<_i5.MonitorServerResponse>>.value(
                _FakeResponseStream_6<_i5.MonitorServerResponse>(
          this,
          Invocation.method(
            #monitorServer,
            [server],
          ),
        )),
      ) as _i10.Future<_i6.ResponseStream<_i5.MonitorServerResponse>>);

  @override
  _i10.Future<_i5.UpdateSubscriptionResponse> updateSubscriptions(
          _i5.UpdateSubscriptionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubscriptions,
          [request],
        ),
        returnValue: _i10.Future<_i5.UpdateSubscriptionResponse>.value(
            _FakeUpdateSubscriptionResponse_8(
          this,
          Invocation.method(
            #updateSubscriptions,
            [request],
          ),
        )),
      ) as _i10.Future<_i5.UpdateSubscriptionResponse>);

  @override
  _i10.Future<void> processGeoFiles() => (super.noSuchMethod(
        Invocation.method(
          #processGeoFiles,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i5.DecodeResponse> decode(String? data) => (super.noSuchMethod(
        Invocation.method(
          #decode,
          [data],
        ),
        returnValue:
            _i10.Future<_i5.DecodeResponse>.value(_FakeDecodeResponse_9(
          this,
          Invocation.method(
            #decode,
            [data],
          ),
        )),
      ) as _i10.Future<_i5.DecodeResponse>);

  @override
  _i10.Future<void> deploy({
    required _i7.SshServer? server,
    _i12.Uint8List? xrayConfig,
    _i12.Uint8List? hysteriaConfig,
    Map<String, _i12.Uint8List>? files,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deploy,
          [],
          {
            #server: server,
            #xrayConfig: xrayConfig,
            #hysteriaConfig: hysteriaConfig,
            #files: files,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i5.GenerateCertResponse> generateCert(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCert,
          [domain],
        ),
        returnValue: _i10.Future<_i5.GenerateCertResponse>.value(
            _FakeGenerateCertResponse_10(
          this,
          Invocation.method(
            #generateCert,
            [domain],
          ),
        )),
      ) as _i10.Future<_i5.GenerateCertResponse>);

  @override
  _i10.Future<void> shutdownServer(_i7.SshServer? server) =>
      (super.noSuchMethod(
        Invocation.method(
          #shutdownServer,
          [server],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> restartServer(_i7.SshServer? server) => (super.noSuchMethod(
        Invocation.method(
          #restartServer,
          [server],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uploadLog(_i5.UploadLogRequest? req) => (super.noSuchMethod(
        Invocation.method(
          #uploadLog,
          [req],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> defaultNICHasGlobalV6() => (super.noSuchMethod(
        Invocation.method(
          #defaultNICHasGlobalV6,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i5.ParseClashRuleFileResponse> parseClashRuleFile(
          List<int>? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseClashRuleFile,
          [content],
        ),
        returnValue: _i10.Future<_i5.ParseClashRuleFileResponse>.value(
            _FakeParseClashRuleFileResponse_11(
          this,
          Invocation.method(
            #parseClashRuleFile,
            [content],
          ),
        )),
      ) as _i10.Future<_i5.ParseClashRuleFileResponse>);

  @override
  _i10.Future<List<_i23.CIDR>> parseGeoIPConfig(_i24.GeoIPConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseGeoIPConfig,
          [config],
        ),
        returnValue: _i10.Future<List<_i23.CIDR>>.value(<_i23.CIDR>[]),
      ) as _i10.Future<List<_i23.CIDR>>);

  @override
  _i10.Future<List<_i23.Domain>> parseGeositeConfig(
          _i24.GeositeConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseGeositeConfig,
          [config],
        ),
        returnValue: _i10.Future<List<_i23.Domain>>.value(<_i23.Domain>[]),
      ) as _i10.Future<List<_i23.Domain>>);

  @override
  _i10.Future<List<_i5.RealiScannerResult>> realiTLScanner(
          String? destination) =>
      (super.noSuchMethod(
        Invocation.method(
          #realiTLScanner,
          [destination],
        ),
        returnValue: _i10.Future<List<_i5.RealiScannerResult>>.value(
            <_i5.RealiScannerResult>[]),
      ) as _i10.Future<List<_i5.RealiScannerResult>>);

  @override
  _i10.Future<(String, String)> generateX25519KeyPair() => (super.noSuchMethod(
        Invocation.method(
          #generateX25519KeyPair,
          [],
        ),
        returnValue: _i10.Future<(String, String)>.value((
          _i17.dummyValue<String>(
            this,
            Invocation.method(
              #generateX25519KeyPair,
              [],
            ),
          ),
          _i17.dummyValue<String>(
            this,
            Invocation.method(
              #generateX25519KeyPair,
              [],
            ),
          )
        )),
      ) as _i10.Future<(String, String)>);

  @override
  _i10.Future<void> setSystemProxy(_i25.SysProxyConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSystemProxy,
          [config],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> stopSystemProxy() => (super.noSuchMethod(
        Invocation.method(
          #stopSystemProxy,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> closeDb() => (super.noSuchMethod(
        Invocation.method(
          #closeDb,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openDb() => (super.noSuchMethod(
        Invocation.method(
          #openDb,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i26.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.AppDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeAppDatabase_12(
          this,
          Invocation.getter(#database),
        ),
      ) as _i7.AppDatabase);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i7.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i8.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_13(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i8.MigrationStrategy);

  @override
  _i7.$SubscriptionsTable get subscriptions => (super.noSuchMethod(
        Invocation.getter(#subscriptions),
        returnValue: _Fake$SubscriptionsTable_14(
          this,
          Invocation.getter(#subscriptions),
        ),
      ) as _i7.$SubscriptionsTable);

  @override
  _i7.$OutboundHandlersTable get outboundHandlers => (super.noSuchMethod(
        Invocation.getter(#outboundHandlers),
        returnValue: _Fake$OutboundHandlersTable_15(
          this,
          Invocation.getter(#outboundHandlers),
        ),
      ) as _i7.$OutboundHandlersTable);

  @override
  _i7.$OutboundHandlerGroupsTable get outboundHandlerGroups =>
      (super.noSuchMethod(
        Invocation.getter(#outboundHandlerGroups),
        returnValue: _Fake$OutboundHandlerGroupsTable_16(
          this,
          Invocation.getter(#outboundHandlerGroups),
        ),
      ) as _i7.$OutboundHandlerGroupsTable);

  @override
  _i7.$OutboundHandlerGroupRelationsTable get outboundHandlerGroupRelations =>
      (super.noSuchMethod(
        Invocation.getter(#outboundHandlerGroupRelations),
        returnValue: _Fake$OutboundHandlerGroupRelationsTable_17(
          this,
          Invocation.getter(#outboundHandlerGroupRelations),
        ),
      ) as _i7.$OutboundHandlerGroupRelationsTable);

  @override
  _i7.$DnsRecordsTable get dnsRecords => (super.noSuchMethod(
        Invocation.getter(#dnsRecords),
        returnValue: _Fake$DnsRecordsTable_18(
          this,
          Invocation.getter(#dnsRecords),
        ),
      ) as _i7.$DnsRecordsTable);

  @override
  _i7.$AtomicDomainSetsTable get atomicDomainSets => (super.noSuchMethod(
        Invocation.getter(#atomicDomainSets),
        returnValue: _Fake$AtomicDomainSetsTable_19(
          this,
          Invocation.getter(#atomicDomainSets),
        ),
      ) as _i7.$AtomicDomainSetsTable);

  @override
  _i7.$GeoDomainsTable get geoDomains => (super.noSuchMethod(
        Invocation.getter(#geoDomains),
        returnValue: _Fake$GeoDomainsTable_20(
          this,
          Invocation.getter(#geoDomains),
        ),
      ) as _i7.$GeoDomainsTable);

  @override
  _i7.$GreatDomainSetsTable get greatDomainSets => (super.noSuchMethod(
        Invocation.getter(#greatDomainSets),
        returnValue: _Fake$GreatDomainSetsTable_21(
          this,
          Invocation.getter(#greatDomainSets),
        ),
      ) as _i7.$GreatDomainSetsTable);

  @override
  _i7.$AtomicIpSetsTable get atomicIpSets => (super.noSuchMethod(
        Invocation.getter(#atomicIpSets),
        returnValue: _Fake$AtomicIpSetsTable_22(
          this,
          Invocation.getter(#atomicIpSets),
        ),
      ) as _i7.$AtomicIpSetsTable);

  @override
  _i7.$GreatIpSetsTable get greatIpSets => (super.noSuchMethod(
        Invocation.getter(#greatIpSets),
        returnValue: _Fake$GreatIpSetsTable_23(
          this,
          Invocation.getter(#greatIpSets),
        ),
      ) as _i7.$GreatIpSetsTable);

  @override
  _i7.$AppSetsTable get appSets => (super.noSuchMethod(
        Invocation.getter(#appSets),
        returnValue: _Fake$AppSetsTable_24(
          this,
          Invocation.getter(#appSets),
        ),
      ) as _i7.$AppSetsTable);

  @override
  _i7.$AppsTable get apps => (super.noSuchMethod(
        Invocation.getter(#apps),
        returnValue: _Fake$AppsTable_25(
          this,
          Invocation.getter(#apps),
        ),
      ) as _i7.$AppsTable);

  @override
  _i7.$CidrsTable get cidrs => (super.noSuchMethod(
        Invocation.getter(#cidrs),
        returnValue: _Fake$CidrsTable_26(
          this,
          Invocation.getter(#cidrs),
        ),
      ) as _i7.$CidrsTable);

  @override
  _i7.$SshServersTable get sshServers => (super.noSuchMethod(
        Invocation.getter(#sshServers),
        returnValue: _Fake$SshServersTable_27(
          this,
          Invocation.getter(#sshServers),
        ),
      ) as _i7.$SshServersTable);

  @override
  _i7.$CommonSshKeysTable get commonSshKeys => (super.noSuchMethod(
        Invocation.getter(#commonSshKeys),
        returnValue: _Fake$CommonSshKeysTable_28(
          this,
          Invocation.getter(#commonSshKeys),
        ),
      ) as _i7.$CommonSshKeysTable);

  @override
  _i7.$CustomRouteModesTable get customRouteModes => (super.noSuchMethod(
        Invocation.getter(#customRouteModes),
        returnValue: _Fake$CustomRouteModesTable_29(
          this,
          Invocation.getter(#customRouteModes),
        ),
      ) as _i7.$CustomRouteModesTable);

  @override
  _i7.$HandlerSelectorsTable get handlerSelectors => (super.noSuchMethod(
        Invocation.getter(#handlerSelectors),
        returnValue: _Fake$HandlerSelectorsTable_30(
          this,
          Invocation.getter(#handlerSelectors),
        ),
      ) as _i7.$HandlerSelectorsTable);

  @override
  _i7.$SelectorHandlerRelationsTable get selectorHandlerRelations =>
      (super.noSuchMethod(
        Invocation.getter(#selectorHandlerRelations),
        returnValue: _Fake$SelectorHandlerRelationsTable_31(
          this,
          Invocation.getter(#selectorHandlerRelations),
        ),
      ) as _i7.$SelectorHandlerRelationsTable);

  @override
  _i7.$SelectorHandlerGroupRelationsTable get selectorHandlerGroupRelations =>
      (super.noSuchMethod(
        Invocation.getter(#selectorHandlerGroupRelations),
        returnValue: _Fake$SelectorHandlerGroupRelationsTable_32(
          this,
          Invocation.getter(#selectorHandlerGroupRelations),
        ),
      ) as _i7.$SelectorHandlerGroupRelationsTable);

  @override
  _i7.$SelectorSubscriptionRelationsTable get selectorSubscriptionRelations =>
      (super.noSuchMethod(
        Invocation.getter(#selectorSubscriptionRelations),
        returnValue: _Fake$SelectorSubscriptionRelationsTable_33(
          this,
          Invocation.getter(#selectorSubscriptionRelations),
        ),
      ) as _i7.$SelectorSubscriptionRelationsTable);

  @override
  _i7.$DnsServersTable get dnsServers => (super.noSuchMethod(
        Invocation.getter(#dnsServers),
        returnValue: _Fake$DnsServersTable_34(
          this,
          Invocation.getter(#dnsServers),
        ),
      ) as _i7.$DnsServersTable);

  @override
  _i7.$AppDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$AppDatabaseManager_35(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i7.$AppDatabaseManager);

  @override
  Iterable<_i8.TableInfo<_i8.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i8.TableInfo<_i8.Table, Object?>>[],
      ) as Iterable<_i8.TableInfo<_i8.Table, Object?>>);

  @override
  List<_i8.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i8.DatabaseSchemaEntity>[],
      ) as List<_i8.DatabaseSchemaEntity>);

  @override
  _i8.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_36(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i8.StreamQueryUpdateRules);

  @override
  _i8.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_37(
          this,
          Invocation.getter(#options),
        ),
      ) as _i8.DriftDatabaseOptions);

  @override
  _i8.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_38(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i8.GeneratedDatabase);

  @override
  _i8.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_39(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i8.DatabaseConnection);

  @override
  _i8.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i17.dummyValue<_i8.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i8.SqlTypes);

  @override
  _i8.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_40(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i8.QueryExecutor);

  @override
  _i9.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_41(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i9.StreamQueryStore);

  @override
  _i8.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_42(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i8.DatabaseConnectionUser);

  @override
  _i10.Future<void> deleteEverything() => (super.noSuchMethod(
        Invocation.method(
          #deleteEverything,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.SelectorConfig> selectorToConfig(
          _i7.HandlerSelector? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectorToConfig,
          [selector],
        ),
        returnValue:
            _i10.Future<_i3.SelectorConfig>.value(_FakeSelectorConfig_1(
          this,
          Invocation.method(
            #selectorToConfig,
            [selector],
          ),
        )),
      ) as _i10.Future<_i3.SelectorConfig>);

  @override
  _i10.Future<_i3.SelectorConfig?> getSelectorConfig(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectorConfig,
          [name],
        ),
        returnValue: _i10.Future<_i3.SelectorConfig?>.value(),
      ) as _i10.Future<_i3.SelectorConfig?>);

  @override
  _i8.TableInfo<_i8.Table, Object?>? getTableByName(String? tableName) =>
      (super.noSuchMethod(Invocation.method(
        #getTableByName,
        [tableName],
      )) as _i8.TableInfo<_i8.Table, Object?>?);

  @override
  _i8.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_43(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i8.Migrator);

  @override
  _i10.Future<void> beforeOpen(
    _i8.QueryExecutor? executor,
    _i8.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Stream<T> createStream<T extends Object>(
          _i9.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i10.Stream<T>.empty(),
      ) as _i10.Stream<T>);

  @override
  T alias<T, D>(
    _i8.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i17.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i8.TableInfo<_i8.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i8.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Stream<Set<_i8.TableUpdate>> tableUpdates(
          [_i8.TableUpdateQuery? query = const _i8.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i10.Stream<Set<_i8.TableUpdate>>.empty(),
      ) as _i10.Stream<Set<_i8.TableUpdate>>);

  @override
  _i10.Future<T> doWhenOpened<T>(
          _i10.FutureOr<T> Function(_i8.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i17.ifNotNull(
              _i17.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_44<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i8.InsertStatement<T, D> into<T extends _i8.Table, D>(
          _i8.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_45<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i8.InsertStatement<T, D>);

  @override
  _i8.UpdateStatement<Tbl, R> update<Tbl extends _i8.Table, R>(
          _i8.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_46<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i8.UpdateStatement<Tbl, R>);

  @override
  _i8.SimpleSelectStatement<T, R> select<T extends _i8.HasResultSet, R>(
    _i8.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_47<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i8.SimpleSelectStatement<T, R>);

  @override
  _i8.JoinedSelectStatement<T, R> selectOnly<T extends _i8.HasResultSet, R>(
    _i8.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_48<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i8.JoinedSelectStatement<T, R>);

  @override
  _i8.BaseSelectStatement<_i8.TypedResult> selectExpressions(
          Iterable<_i8.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_49<_i8.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i8.BaseSelectStatement<_i8.TypedResult>);

  @override
  _i8.DeleteStatement<T, D> delete<T extends _i8.Table, D>(
          _i8.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_50<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i8.DeleteStatement<T, D>);

  @override
  _i10.Future<int> customUpdate(
    String? query, {
    List<_i8.Variable<Object>>? variables = const [],
    Set<_i8.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i8.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> customInsert(
    String? query, {
    List<_i8.Variable<Object>>? variables = const [],
    Set<_i8.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<List<_i8.QueryRow>> customWriteReturning(
    String? query, {
    List<_i8.Variable<Object>>? variables = const [],
    Set<_i8.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i8.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i10.Future<List<_i8.QueryRow>>.value(<_i8.QueryRow>[]),
      ) as _i10.Future<List<_i8.QueryRow>>);

  @override
  _i8.Selectable<_i8.QueryRow> customSelect(
    String? query, {
    List<_i8.Variable<Object>>? variables = const [],
    Set<_i8.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_51<_i8.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i8.Selectable<_i8.QueryRow>);

  @override
  _i8.Selectable<_i8.QueryRow> customSelectQuery(
    String? query, {
    List<_i8.Variable<Object>>? variables = const [],
    Set<_i8.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_51<_i8.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i8.Selectable<_i8.QueryRow>);

  @override
  _i10.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<T> transaction<T>(
    _i10.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i17.ifNotNull(
              _i17.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_44<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i10.Future<T> exclusively<T>(_i10.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i17.ifNotNull(
              _i17.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_44<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i10.Future<void> batch(
          _i10.FutureOr<void> Function(_i8.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<T> runWithInterceptor<T>(
    _i10.Future<T> Function()? action, {
    required _i8.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i17.ifNotNull(
              _i17.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_44<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i8.GenerationContext $write(
    _i8.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_52(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i8.GenerationContext);

  @override
  _i8.GenerationContext $writeInsertable(
    _i8.TableInfo<_i8.Table, dynamic>? table,
    _i8.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_52(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i8.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [AtomicDomainSet].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtomicDomainSet extends _i1.Mock implements _i7.AtomicDomainSet {
  MockAtomicDomainSet() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get useBloomFilter => (super.noSuchMethod(
        Invocation.getter(#useBloomFilter),
        returnValue: false,
      ) as bool);

  @override
  Map<String, _i8.Expression<Object>> toColumns(bool? nullToAbsent) =>
      (super.noSuchMethod(
        Invocation.method(
          #toColumns,
          [nullToAbsent],
        ),
        returnValue: <String, _i8.Expression<Object>>{},
      ) as Map<String, _i8.Expression<Object>>);

  @override
  _i7.AtomicDomainSetsCompanion toCompanion(bool? nullToAbsent) =>
      (super.noSuchMethod(
        Invocation.method(
          #toCompanion,
          [nullToAbsent],
        ),
        returnValue: _FakeAtomicDomainSetsCompanion_53(
          this,
          Invocation.method(
            #toCompanion,
            [nullToAbsent],
          ),
        ),
      ) as _i7.AtomicDomainSetsCompanion);

  @override
  Map<String, dynamic> toJson({_i8.ValueSerializer? serializer}) =>
      (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
          {#serializer: serializer},
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String toJsonString({_i8.ValueSerializer? serializer}) => (super.noSuchMethod(
        Invocation.method(
          #toJsonString,
          [],
          {#serializer: serializer},
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #toJsonString,
            [],
            {#serializer: serializer},
          ),
        ),
      ) as String);
}

/// A class which mocks [AppSet].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSet extends _i1.Mock implements _i7.AppSet {
  MockAppSet() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  Map<String, _i8.Expression<Object>> toColumns(bool? nullToAbsent) =>
      (super.noSuchMethod(
        Invocation.method(
          #toColumns,
          [nullToAbsent],
        ),
        returnValue: <String, _i8.Expression<Object>>{},
      ) as Map<String, _i8.Expression<Object>>);

  @override
  _i7.AppSetsCompanion toCompanion(bool? nullToAbsent) => (super.noSuchMethod(
        Invocation.method(
          #toCompanion,
          [nullToAbsent],
        ),
        returnValue: _FakeAppSetsCompanion_54(
          this,
          Invocation.method(
            #toCompanion,
            [nullToAbsent],
          ),
        ),
      ) as _i7.AppSetsCompanion);

  @override
  Map<String, dynamic> toJson({_i8.ValueSerializer? serializer}) =>
      (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
          {#serializer: serializer},
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String toJsonString({_i8.ValueSerializer? serializer}) => (super.noSuchMethod(
        Invocation.method(
          #toJsonString,
          [],
          {#serializer: serializer},
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #toJsonString,
            [],
            {#serializer: serializer},
          ),
        ),
      ) as String);
}

/// A class which mocks [AtomicIpSet].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtomicIpSet extends _i1.Mock implements _i7.AtomicIpSet {
  MockAtomicIpSet() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get inverse => (super.noSuchMethod(
        Invocation.getter(#inverse),
        returnValue: false,
      ) as bool);

  @override
  Map<String, _i8.Expression<Object>> toColumns(bool? nullToAbsent) =>
      (super.noSuchMethod(
        Invocation.method(
          #toColumns,
          [nullToAbsent],
        ),
        returnValue: <String, _i8.Expression<Object>>{},
      ) as Map<String, _i8.Expression<Object>>);

  @override
  _i7.AtomicIpSetsCompanion toCompanion(bool? nullToAbsent) =>
      (super.noSuchMethod(
        Invocation.method(
          #toCompanion,
          [nullToAbsent],
        ),
        returnValue: _FakeAtomicIpSetsCompanion_55(
          this,
          Invocation.method(
            #toCompanion,
            [nullToAbsent],
          ),
        ),
      ) as _i7.AtomicIpSetsCompanion);

  @override
  Map<String, dynamic> toJson({_i8.ValueSerializer? serializer}) =>
      (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
          {#serializer: serializer},
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String toJsonString({_i8.ValueSerializer? serializer}) => (super.noSuchMethod(
        Invocation.method(
          #toJsonString,
          [],
          {#serializer: serializer},
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #toJsonString,
            [],
            {#serializer: serializer},
          ),
        ),
      ) as String);
}
